import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer, Header } from '@/widgets';

import './styles/globals.css';
import { cn } from '@/shared/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Shoppe Store',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={cn('not-scroll', inter.className)}>
                <main className='flex flex-col min-h-screen py-12 px-4 m-auto max-w-[1280px] not-scroll'>
                    <Header />
                    {children}
                    <Footer />
                </main>
            </body>
        </html>
    );
}
